name: deploy/prod

on:
  release:
    types: [published]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DO_ADMIN_API_ACCESS_TOKEN }}
